name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Set up Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      id: node

    - name: Set up gulp
      run: |
        npm install gulp

    - name: Build
      run: |
        echo "Building ..."
        echo "go"
        go version
        echo "node"
        node --version
        echo "npm"
        npm -v
        echo "yarn"
        yarn -v
        echo "gulp"
        gulp -v

